// Generated by CoffeeScript 1.6.3
(function() {
  var $, Backbone, Pouch, Routes, View, spin, start, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    _this = this;

  Backbone = require('backbone');

  $ = require('jquery');

  Backbone.$ = $;

  View = require('./view');

  Pouch = require('pouchdb');

  spin = require('spin');

  require('bootstrap');

  Routes = (function(_super) {
    __extends(Routes, _super);

    function Routes() {
      _ref = Routes.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Routes.prototype.initialize = function(opts) {
      return this.body = opts.body;
    };

    Routes.prototype.routes = {
      'c:type': 'nStyle',
      'y:type': 'session',
      'SessionLaw': 'years',
      'SessionLaw/Year:year': 'years',
      ':type': 'roo',
      ':type/Part:part': 'roo',
      ':type/Part:part/Title:title': 'roo',
      ':type/Part:part/Title:title/Chapter:chapter': 'roo',
      ':type/Part:part/Title:title/Chapter:chapter/Section:section': 'roo',
      'q/:query': 'qoo',
      '*spat': 'roo'
    };

    Routes.prototype.roo = function(type, part, title, chapter, section) {
      var parts;
      if (type == null) {
        type = 'home';
      }
      if (part == null) {
        part = 'all';
      }
      if (title == null) {
        title = 'all';
      }
      if (chapter == null) {
        chapter = 'all';
      }
      if (section == null) {
        section = 'all';
      }
      this.body.spin();
      parts = {
        type: type,
        part: part,
        title: title,
        chapter: chapter,
        section: section
      };
      if (parts.chapter !== 'all') {
        parts.chapter = parseInt(parts.chapter, 10);
      }
      if (parts.section !== 'all') {
        parts.section = parseInt(parts.section, 10);
      }
      return this.body.render(parts);
    };

    Routes.prototype.qoo = function(query) {
      this.body.spin();
      return this.body.render({
        q: query
      });
    };

    Routes.prototype.nStyle = function(path) {
      var parts, split;
      this.body.spin();
      if (__indexOf.call(path, 's') >= 0) {
        split = path.split('s');
        parts = {
          newStyleName: true,
          c: split[0],
          s: split[1]
        };
        return this.body.render(parts);
      } else if (__indexOf.call(path, 'a') >= 0) {
        split = path.split('a');
        parts = {
          c: split[0],
          a: split[1]
        };
        return this.body.render(parts);
      }
    };

    Routes.prototype.session = function(path) {
      var parts, split;
      this.body.spin();
      if (__indexOf.call(path, 'c') >= 0) {
        split = path.split('c');
        parts = {
          y: split[0],
          c: split[1]
        };
        return this.body.render(parts);
      }
    };

    Routes.prototype.years = function(year) {
      if (year == null) {
        year = 'all';
      }
      this.body.spin();
      return this.body.render({
        type: 'session',
        year: year
      });
    };

    return Routes;

  })(Backbone.Router);

  start = function(dbname) {
    return Pouch("" + location.protocol + "//" + location.host + "//law", function(err, db) {
      window.body = new View({
        db: db,
        el: $('#mainContent')
      });
      window.routes = new Routes({
        body: window.body
      });
      Backbone.history.start({
        pushState: true,
        hashChange: false,
        root: '/law/_design/laws/_rewrite/'
      });
      true;
      $('#searchForm').on('submit', function(e) {
        e.preventDefault();
        return routes.navigate('q/' + $('#searchBox').val(), {
          trigger: true
        });
      });
      return $('.menulinks').on('click', function(a) {
        a.preventDefault();
        return routes.navigate(a.target.id, {
          trigger: true
        });
      });
    });
  };

  start('law');

}).call(this);
