// Generated by CoffeeScript 1.6.3
(function() {
  var $, Backbone, Pouch, Routes, View, body, db, routes, spin, start, templates, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    _this = this;

  Backbone = require('backbone');

  $ = require('jquery');

  Backbone.$ = $;

  templates = require('./templates');

  Pouch = require('pouchdb');

  spin = require('spin');

  require('bootstrap');

  db = false;

  View = (function(_super) {
    __extends(View, _super);

    function View() {
      _ref = View.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    View.prototype.events = {
      'click .bodyLink': 'movePage'
    };

    View.prototype.search = function(q) {
      var opts, path;
      path = "" + (db.id()) + "_design/laws/_search/sections";
      opts = {
        q: q,
        include_docs: true,
        limit: 200
      };
      return $.ajax(path, {
        data: opts,
        dataType: 'json'
      });
    };

    View.prototype.movePage = function(a) {
      a.preventDefault();
      return routes.navigate(a.target.id, {
        trigger: true
      });
    };

    View.prototype.spin = function(a) {
      return this.$el.spin(a);
    };

    View.prototype.template = templates;

    View.prototype.render = function(loc) {
      var id, opts, type;
      if ('q' in loc) {
        return this.search(loc.q).then(function(resp) {
          console.log(resp);
          resp.q = loc.q;
          body.spin(false);
          return body.$el.html(body.template.search(resp));
        });
      } else if ('newStyleName' in loc) {
        id = "c" + loc.c + "s" + loc.s;
        return db.get(id, function(err, doc) {
          if (err) {
            body.spin(false);
          } else {
            body.spin(false);
            return body.$el.html(body.template.section(doc));
          }
        });
      } else if ('a' in loc) {
        id = "c" + loc.c + "a" + loc.a;
        return db.get(id, function(err, doc) {
          if (err) {
            body.spin(false);
          } else {
            body.spin(false);
            return body.$el.html(body.template.article(doc));
          }
        });
      } else if ('y' in loc) {
        id = "y" + loc.y + "c" + loc.c;
        return db.get(id, function(err, doc) {
          if (err) {
            body.spin(false);
          } else {
            body.spin(false);
            return body.$el.html(body.template.session(doc));
          }
        });
      } else if (loc.type && loc.type === 'session') {
        if (loc.year === 'all') {
          opts = {
            startkey: [loc.type],
            endkey: [loc.type, {}],
            group_level: 2
          };
          return db.query("laws/sessions", opts, function(err, resp) {
            resp.rows = resp.rows.map(function(row) {
              var out;
              out = {};
              out.year = row.key.pop();
              return out;
            });
            body.spin(false);
            return body.$el.html(body.template.sess(resp));
          });
        } else {
          opts = {
            startkey: [loc.type, parseInt(loc.year, 10)],
            endkey: [loc.type, parseInt(loc.year, 10), {}],
            reduce: false,
            include_docs: true
          };
          return db.query("laws/sessions", opts, function(err, resp) {
            resp.rows.sort(function(a, b) {
              return a.doc.chapter - b.doc.chapter;
            });
            resp.year = loc.year;
            body.spin(false);
            return body.$el.html(body.template.year(resp));
          });
        }
      } else if (loc.section !== 'all') {
        id = "c" + loc.chapter + "s" + loc.section;
        return db.get(id, function(err, doc) {
          if (err) {
            body.spin(false);
          } else {
            body.spin(false);
            return body.$el.html(body.template.section(doc));
          }
        });
      } else if (loc.section === 'all' && loc.chapter !== 'all') {
        if (loc.type = 'GeneralLaws') {
          type = 'general';
        } else {
          type = loc.type;
        }
        opts = {
          startkey: [type, loc.part, loc.title, loc.chapter.toString()],
          endkey: [type, loc.part, loc.title, loc.chapter.toString(), {}],
          reduce: false,
          include_docs: true
        };
        return db.query("laws/all", opts, function(err, resp) {
          resp.rows = resp.rows.map(function(item) {
            if (item.doc.section) {
              item.doc.sub = item.doc.section;
              item.doc.shortCode = "s";
              item.doc.longCode = "Section";
            } else if (item.doc.article) {
              item.doc.sub = item.doc.article;
              item.doc.shortCode = "a";
              item.doc.longCode = "Article";
            }
            return item;
          });
          resp.chap = loc.chapter;
          resp.tit = loc.title;
          resp.pat = loc.part;
          body.spin(false);
          return body.$el.html(body.template.chapter(resp));
        });
      } else if (loc.chapter === 'all' && loc.title !== 'all') {
        if (loc.type = 'GeneralLaws') {
          type = 'general';
        } else {
          type = loc.type;
        }
        opts = {
          startkey: [type, loc.part, loc.title],
          endkey: [type, loc.part, loc.title, {}],
          group_level: 4
        };
        return db.query("laws/all", opts, function(err, resp) {
          var rows;
          rows = resp.rows.map(function(row) {
            var out;
            out = {};
            out.chapter = row.key.pop();
            out.title = row.key.pop();
            out.part = row.key.pop();
            return out;
          });
          body.spin(false);
          return body.$el.html(body.template.title({
            row: rows,
            t: loc.title,
            tp: loc.part
          }));
        });
      } else if (loc.title === 'all' && loc.part !== 'all') {
        if (loc.type = 'GeneralLaws') {
          type = 'general';
        } else {
          type = loc.type;
        }
        opts = {
          startkey: [type, loc.part],
          endkey: [type, loc.part, {}],
          group_level: 3
        };
        return db.query("laws/all", opts, function(err, resp) {
          var rows;
          rows = resp.rows.map(function(row) {
            var out;
            out = {};
            out.title = row.key.pop();
            out.part = row.key.pop();
            return out;
          });
          body.spin(false);
          return body.$el.html(body.template.part({
            rowp: rows,
            p: loc.part
          }));
        });
      } else {
        type = 'general';
        opts = {
          startkey: [type],
          endkey: [type, {}],
          group_level: 2
        };
        return db.query("laws/all", opts, function(err, resp) {
          var rows;
          rows = resp.rows.map(function(row) {
            var out;
            out = {};
            out.part = row.key.pop();
            return out;
          });
          body.spin(false);
          return body.$el.html(body.template.general({
            rowg: rows,
            g: true
          }));
        });
      }
    };

    return View;

  })(Backbone.View);

  body = new View({
    el: $('#mainContent')
  });

  window.body = body;

  Routes = (function(_super) {
    __extends(Routes, _super);

    function Routes() {
      _ref1 = Routes.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Routes.prototype.routes = {
      'c:type': 'nStyle',
      'y:type': 'session',
      'SessionLaw': 'years',
      'SessionLaw/Year:year': 'years',
      ':type': 'roo',
      ':type/Part:part': 'roo',
      ':type/Part:part/Title:title': 'roo',
      ':type/Part:part/Title:title/Chapter:chapter': 'roo',
      ':type/Part:part/Title:title/Chapter:chapter/Section:section': 'roo',
      'q/:query': 'qoo',
      '*spat': 'roo'
    };

    Routes.prototype.roo = function(type, part, title, chapter, section) {
      var parts;
      if (type == null) {
        type = 'home';
      }
      if (part == null) {
        part = 'all';
      }
      if (title == null) {
        title = 'all';
      }
      if (chapter == null) {
        chapter = 'all';
      }
      if (section == null) {
        section = 'all';
      }
      body.spin();
      parts = {
        type: type,
        part: part,
        title: title,
        chapter: chapter,
        section: section
      };
      if (parts.chapter !== 'all') {
        parts.chapter = parseInt(parts.chapter, 10);
      }
      if (parts.section !== 'all') {
        parts.section = parseInt(parts.section, 10);
      }
      return body.render(parts);
    };

    Routes.prototype.qoo = function(query) {
      body.spin();
      return body.render({
        q: query
      });
    };

    Routes.prototype.nStyle = function(path) {
      var parts, split;
      body.spin();
      if (__indexOf.call(path, 's') >= 0) {
        split = path.split('s');
        parts = {
          newStyleName: true,
          c: split[0],
          s: split[1]
        };
        return body.render(parts);
      } else if (__indexOf.call(path, 'a') >= 0) {
        split = path.split('a');
        parts = {
          c: split[0],
          a: split[1]
        };
        return body.render(parts);
      }
    };

    Routes.prototype.session = function(path) {
      var parts, split;
      body.spin();
      if (__indexOf.call(path, 'c') >= 0) {
        split = path.split('c');
        parts = {
          y: split[0],
          c: split[1]
        };
        return body.render(parts);
      }
    };

    Routes.prototype.years = function(year) {
      if (year == null) {
        year = 'all';
      }
      body.spin();
      return body.render({
        type: 'session',
        year: year
      });
    };

    return Routes;

  })(Backbone.Router);

  routes = new Routes;

  /*nav = new View
  	render:(location)->
  		true
  	template:"""
  		<ul>
  		{{#items}}
  		
  		{{/items}}
  		</ul>
  	"""
  	el:$ '#navBar'
  */


  start = function(dbname) {
    db = Pouch("" + location.protocol + "//" + location.host + "//law", function(err, rslt) {
      Backbone.history.start({
        pushState: true,
        hashChange: false,
        root: '/law/_design/laws/_rewrite/'
      });
      return window.db = db;
    });
    return $('#searchForm').on('submit', function(e) {
      e.preventDefault();
      return routes.navigate('q/' + $('#searchBox').val(), {
        trigger: true
      });
    });
  };

  start('law');

}).call(this);
